title: "Shashank Shekhar: Full Stack Web Developer"
description: "A lazy web developer who codes in JavaScript whether be frontend or backend but also have idea to work with
  Java, Android, Python & C. His self taughting skills have made him a better developer and a better person too.
  Shoot him a message, if any help needed, He will be glad to help you."
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://shashank7200.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shashank Shekhar
author-img: shashank-shekhar.jpg # add your photo
about-author: I am a full stack web developer. Always hungry to keep learning. Shoot me a message, if any help needed. # add description
twitter: shankywit # add your Twitter handle
facebook: vishami3 # add your Facebook handle
github: shashank7200 # add your Github handle
linkedin: shashankshekharofficial # add your Linkedin handle
email: shashank7200@gmail.com # add your Email address

# Disqus
discus-identifier: shashank-shekhar # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
